mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('api/list', include('polls.api.urls')),




] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/api/urls.py
from django.urls import path
from polls.api.views import (
    AlbumListAPIView
)

urlpatterns = [
    
    #/music 
    path('', AlbumListAPIView.as_view() , name='index'),
    
]

polls/urls.py
from django.urls import path
from . import views

app_name='polls'
urlpatterns = [
    
    #/music 
    path('', views.indexView.as_view() , name='index'),
    #/music/22/
    path('<album_id>/', views.indexDetail.as_view(), name='detail'),
    #user
    path('user/register/', views.register, name='register'),
    path('user/login/', views.login_user, name='login'),
    path('user/logout/', views.logout_user, name='logout'),
    #/music/album/add
    path('album/add/', views.AlbumCreate.as_view(), name='album-add'),
    #/music/album/add
    path('album/<album_id>/delete', views.AlbumDelete.as_view(), name='album-delete'),
    #create_song
    path('<album_id>/createsong/', views.CreateSong, name='createsong'),

]

polls/models.py
from django.contrib.auth.models import User
from django.db import models


class Album(models.Model):
    user = models.ForeignKey(User, default=1 , on_delete=models.CASCADE)
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def __str__(self):
        return self.album_title + ' - ' + self.artist



class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=250)
    audio_file = models.FileField()

    def __str__(self):
        return self.song_title

polls/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Album, Song


class AlbumForm(forms.ModelForm):

    class Meta:
        model = Album
        fields = ['artist', 'album_title', 'genre', 'album_logo']

class SongForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ['song_title', 'audio_file']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

polls/api/views.py
from rest_framework.generics import ListAPIView
from polls.models import Album
from .serializers import AlbumSerializer

class AlbumListAPIView(ListAPIView):
    queryset = Album.objects.all()
    serializer_class = AlbumSerializer

polls/views.py
from django.views import generic
from django import forms
from django.views.generic.edit import CreateView, DeleteView
from .models import Album
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from django.urls import reverse_lazy, reverse
from .forms import UserForm, SongForm


class indexView(generic.ListView):
    template_name = 'music/index.html'
    def get_queryset(self):
        return Album.objects.all()

class indexDetail(generic.DetailView):
    model=Album
    pk_url_kwarg = 'album_id'
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model=Album
    fields=['artist', 'album_title', 'genre', 'album_logo']
    template_name='music/album_form.html'
    success_url = reverse_lazy('polls:index')

class AlbumDelete(DeleteView):
    model=Album
    pk_url_kwarg = 'album_id'
    success_url=reverse_lazy('polls:index')

def logout_user(request):
    logout(request)
    return redirect('/polls')


def login_user(request):
    form = UserForm(request.POST or None)
    title = "Login"
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                return redirect('/polls', {'albums': albums})
            else:
                return render(request, 'music/SignUp.html', {"form": form, "title":title})
        else:
            return render(request, 'music/SignUp.html', {"form": form, "title":title})
    return render(request,'music/SignUp.html',{"form": form, "title":title})

def register(request):
    form = UserForm(request.POST or None)
    title = "Register"
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'music/index.html')
    context = {
        "form": form,
        "title":title
    }
    return render(request, 'music/SignUp.html', context)

def CreateSong(request, album_id):
    form = SongForm(request.POST or None, request.FILES or None)
    album = get_object_or_404(Album, pk=album_id)
    AUDIO_FILE_TYPES = ['mp3']
    if form.is_valid():
        song = form.save(commit=False)
        song.album = album
        song.audio_file = request.FILES['audio_file']
        file_type = song.audio_file.url.split('.')[-1]
        if file_type not in AUDIO_FILE_TYPES:
            raise forms.ValidationError("Audio file must be  MP3") 
        else:
            song.save()
            return render(request, 'music/detail.html', {'album': album})
        
    context = {
        'album': album,
        'form': form,
    }
    return render(request, 'music/song_form.html', context)

polls/templates/music/SignUp.html
{% extends "music/base.html" %}
{% block body %}

  <h2>{{ title }}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' class='btn btn-default' value='{{ title }}' />
  </form>
{% endblock %}

polls/templates/music/album_form.html
{% extends "music/base.html" %}
{% block body %}
<h1>Add a New Album</h1>
<div class="continer-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include "music/form-template.html" %}
                        <div class="form-group" >
                            <div class="col-sm-offset-2 col-sm-10">
                              <button type="submit" class="btn btn-success">Submit</button>

                            </div>

                        </div>

                    </form>

                </div>

            </div>
            
        </div>
    </div>
    




</div>




{% endblock %}

polls/templates/music/base.html
<!doctype html>
<html lang="en">
  <head>
    <title>Music App</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- load static files -->
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href= "/media/new.css" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Monoton">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald:400,700">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Pacifico">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Permanent+Marker">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sigmar+One">


  </head>

  
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header"><a class="navbar-brand navbar-link" href="{% url 'polls:index'  %}">Music App</a>
                <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
            </div>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav">
                    <li role="presentation"><a href="{% url 'polls:index'  %}" class="albums"><i class="glyphicon glyphicon-cd"></i> Albums </a></li>
                    <li role="presentation"><a href="{% url 'polls:register'  %}" style="font-family:'Sigmar One'; left:600px;"><i class="glyphicon glyphicon-user"></i> SignUp </a></li>
                    <li role="presentation"><a href="{% url 'polls:login'  %}" class="add new" style="left:620px;" >&nbsp;<i class="glyphicon glyphicon-log-in"></i>&nbsp; login</a></li>
                    <li role="presentation" class="log out"><a href="{% url 'polls:logout'  %}" style="font-family:'Sigmar One';"><i class="glyphicon glyphicon-off"></i> Logout</a></li>
                    <li role="presentation"id="add_album"><a href="{% url 'polls:album-add'  %}" style="font-family:'Sigmar One'; right:150px;"><i class="glyphicon glyphicon-plus"></i> Add Album</a></li>
                </ul>
            </div>
        </div>
    </nav>
    

        
        <div class="search"><input type="search" class="search"><i class="glyphicon glyphicon-search"></i></div>

    {% block body %}

    
    {% endblock body %}
    

        <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  </body>
</html>

polls/templates/music/detail.html
{% extends "music/base.html" %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'polls:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin: 20px;">
                <li role="presentation"><a href="{%url 'polls:createsong' album.id %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a target="_blank" href="{{ song.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class=class="glyphicon glyphicon-download"></span>&nbsp; Download
                                        </button>
                                    </a>
                                </td>
                            
                                    
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

polls/templates/music/form-template.html
{% for field in form %}
<div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" style="color:black;">{{ field.label_tag }}</label>
        <div class="col-sm-10"style="color:black;">{{ field }}</div>
</div>
{% endfor %}

polls/templates/music/form.html
{% extends "music/base.html" %}
{% block body %}
<div class="col-sm-6 col-sm-offset-3" style="position:relative;top:7em" >
        <h1 class=".lead">{{ title }}</h1>
        <hr/>
<form method="POST"  enctype="multipart/form-data">
{% csrf_token %}
<input type="submit" class="btn btn-default" value='{{ title }}'/>

</form>
</div>

  
{% endblock %}

polls/templates/music/index.html
{% extends "music/base.html" %}

{% block body %}
<ul class="listone">
    <p style="float:right; margin:.3em 15em 0 0;">Hello {{ user.username }}</p>

    {% for album in object_list %}
    <il >
            <div class="album1" style="float:left; margin:2em">
        <a href="{% url 'polls:detail' album.id  %}" target="_parent" class="linkdiv1"> <img src="{{album.album_logo.url}}"  class="red"> </a>
                    <div class="btn-group" role="group" id="groupbtn1">
                        <form method="get" action="{% url 'polls:detail' album.id  %}"class="form1">
                            <button class="btn btn-primary" type="submit">View Details</button>
                        </form>
                        <form action="{% url 'polls:album-delete' album.id %}" method="POST" class="form1">
                            {% csrf_token %}
                            <input type="hidden" value="{{album.id}}"/>
                            <button class="btn btn-default" type="submit" > <i class="glyphicon glyphicon-trash"></i></button>
                        </form>
                    </div>
                </div>
                </il>
                
                {% endfor %} 
</ul>
{% endblock %}
    

polls/templates/music/registration_form.html
{% extends "music/base.html" %}
{% block body %}
<h1>Create A New Account</h1>
<div class="continer-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include "music/form-template.html" %}
                        <div class="form-group" >
                            <div class="col-sm-offset-2 col-sm-10">
                              <button type="submit" class="btn btn-success">Submit</button>

                            </div>

                        </div>

                    </form>

                </div>

            </div>
            
        </div>
    </div>
    




</div>




{% endblock %}

polls/templates/music/song_form.html
{% extends "music/base.html" %}
{% block body %}
<h1>Add a Song</h1>
<div class="continer-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                        
                        {% csrf_token %}
                        {% include "music/form-template.html" %}
                        <div class="form-group" >
                                <span class="text-danger small">{{ field.error_message }}</span>
                            <div class="col-sm-offset-2 col-sm-10">
                              <button type="submit" class="btn btn-success">Submit</button>

                            </div>

                        </div>

                    </form>

                </div>

            </div>
            
        </div>
    </div>
    




</div>




{% endblock %}